static_library("01_example") {
    sources = [
        "01_example.c",
        "//vendor/hqyj/fs_hi3861/common/bsp/src/hal_bsp_pcf8574.c"
    ]

    include_dirs = [
        "//utils/native/lite/include",
        "//kernel/liteos_m/kal/cmsis",
        "//base/iot_hardware/peripheral/interfaces/kits",
        "//vendor/hqyj/fs_hi3861/common/bsp/include"
    ]
}